In [1]:
import numpy as np
import pandas as pd

In [2]:
dfavgtur = pd.read_excel('../data/chmi/B2BTUR01.xlsx', sheet_name='teplota průměrná', header=3)
dfmaxtur = pd.read_excel('../data/chmi/B2BTUR01.xlsx', sheet_name='teplota maximální', header=3)
dfmintur = pd.read_excel('../data/chmi/B2BTUR01.xlsx', sheet_name='teplota minimální', header=3)

In [3]:
dfavgtur.head()

,rok,měsíc,1.,2.,3.,4.,5.,6.,7.,8.,...,22.,23.,24.,25.,26.,27.,28.,29.,30.,31.
0,1961,1,-0.8,-0.4,1.5,2.1,1.1,1.4,-0.3,0.8,...,-4.4,-3.2,-4.9,-7.0,-10.3,-9.4,-7.6,-6.8,-3.2,1.1
1,1961,2,1.7,1.3,1.9,0.6,-1.7,-3.3,-1.2,0.7,...,3.2,4.3,3.7,1.8,0.8,3.3,3.8,NaN,NaN,NaN
2,1961,3,2.8,1.9,3.7,4.7,4.9,5.0,7.1,7.8,...,-0.4,4.8,7.8,8.5,8.2,5.7,2.0,4.7,7.4,7.3
3,1961,4,8.2,9.6,9.6,9.5,13.8,15.0,17.2,14.2,...,10.8,11.2,12.1,10.8,13.6,13.3,11.0,12.5,13.1,NaN
4,1961,5,13.7,13.2,12.6,13.4,15.9,16.3,15.8,10.0,...,13.6,12.1,14.9,16.8,17.9,17.1,11.3,10.4,9.6,14.8

In [4]:
days = pd.date_range(start='01/01/1961', end='31/12/2021')
dfavgtur.index = pd.MultiIndex.from_arrays(dfavgtur[['rok', 'měsíc']].values.T)
df2 = pd.DataFrame({'date': days})

/home/ondras/Jupyter/data-analysis/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3251: UserWarning: Parsing '31/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
df2.head()

        date
0 1961-01-01
1 1961-01-02
2 1961-01-03
3 1961-01-04
4 1961-01-05

In [6]:
def lookupavg(dt):
    return dfavgtur.loc[dt.year, dt.month][str(dt.day) + '.']
def lookupmax(dt):
    return dfmaxtur.loc[dt.year, dt.month][str(dt.day) + '.']
def lookupmin(dt):
    return dfmintur.loc[dt.year, dt.month][str(dt.day) + '.']

In [7]:
df2['tempavg'] = df2['date'].apply(lookupavg)
df2['tempmax'] = df2['date'].apply(lookupmax)
df2['tempmin'] = df2['date'].apply(lookupmin)

KeyError: 1

In [ ]:
dfavgtur.loc[1961,1][str(1)+'.']

In [ ]:
df2.head()

In [ ]:
import seaborn as sns

sns.lineplot(data=df2.iloc[:730], x='date', y='temp')